/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dao.Conexion;
import dao.ProductosDAO;
import interfaces.IConexionDB;
import interfaces.IProductosDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Producto;

/**
 *
 * @author Aaron
 */
public class FrmProductos extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
        conexion = new Conexion();
        productos = new ProductosDAO(conexion);
        conversion = new Conversion();
        campoTextoDescripcion.setLineWrap(true);
        campoTextoDescripcion.setWrapStyleWord(true);
        actualizarVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoTextoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoTextoPrecio = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoTextoDescripcion = new javax.swing.JTextArea();
        botonCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Productos");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setResizable(false);
        setSize(getPreferredSize());

        tablaProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);
        if (tablaProductos.getColumnModel().getColumnCount() > 0) {
            tablaProductos.getColumnModel().getColumn(1).setResizable(false);
            tablaProductos.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nombre");

        campoTextoNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Descripcion");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Precio");

        campoTextoPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        botonAgregar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.setMaximumSize(getPreferredSize());
        botonAgregar.setMinimumSize(getPreferredSize());
        botonAgregar.setPreferredSize(new java.awt.Dimension(150, 40));
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        campoTextoDescripcion.setColumns(20);
        campoTextoDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoTextoDescripcion.setRows(5);
        jScrollPane2.setViewportView(campoTextoDescripcion);

        botonCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setMaximumSize(getPreferredSize());
        botonCancelar.setMinimumSize(getPreferredSize());
        botonCancelar.setPreferredSize(new java.awt.Dimension(150, 40));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Ctrl + Click para deseleccionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(campoTextoNombre)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(campoTextoPrecio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTextoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarVentana() {
        int r = tablaProductos.getSelectedRow();
        tablaProductos.setModel(conversion.productosTableModel(productos.consultarTodos()));
        if(botonAgregar.getText().equals("Actualizar")) {
            tablaProductos.setRowSelectionInterval(r, r);
        }else if(botonAgregar.getText().equals("Agregar")) {
            campoTextoNombre.setText(null);
            campoTextoDescripcion.setText(null);
            campoTextoPrecio.setText(null);
        }
    }
    
    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        int fila = tablaProductos.getSelectedRow();
        
        if(fila != -1) {
            DefaultTableModel model = (DefaultTableModel)tablaProductos.getModel();
            campoTextoNombre.setText(model.getValueAt(fila, 1).toString());
            campoTextoDescripcion.setText(model.getValueAt(fila, 2).toString());
            campoTextoPrecio.setText(model.getValueAt(fila, 3).toString());
        
            botonAgregar.setText("Actualizar");
            botonCancelar.setText("Eliminar");
        }else {
            botonAgregar.setText("Agregar");
            botonCancelar.setText("Cancelar");
            campoTextoNombre.setText(null);
            campoTextoDescripcion.setText(null);
            campoTextoPrecio.setText(null);
        }
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        if(botonAgregar.getText().equals("Agregar")) {
            if((campoTextoNombre.getText().isEmpty() || campoTextoDescripcion.getText().isEmpty()) || campoTextoPrecio.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor llena todos los campos", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            }else {
                Producto producto = new Producto();
                producto.setNombre(campoTextoNombre.getText());
                producto.setDescripcion(campoTextoDescripcion.getText());
                producto.setPrecio(Double.parseDouble(campoTextoPrecio.getText()));
                productos.agregar(producto);
            }
        }else if(botonAgregar.getText().equals("Actualizar")) {
            if((campoTextoNombre.getText().isEmpty() || campoTextoDescripcion.getText().isEmpty()) || campoTextoPrecio.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor llena todos los campos", "Advertencia", JOptionPane.INFORMATION_MESSAGE);
            }else {
                Producto producto = new Producto();
                producto.setId(Integer.parseInt(tablaProductos.getValueAt(tablaProductos.getSelectedRow(), 0).toString()));
                producto.setNombre(campoTextoNombre.getText());
                producto.setDescripcion(campoTextoDescripcion.getText());
                producto.setPrecio(Double.parseDouble(campoTextoPrecio.getText()));
                productos.actualizar(producto);
            }
        }
        
        actualizarVentana();
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        if(botonCancelar.getText().equals("Cancelar")) {
            campoTextoNombre.setText(null);
            campoTextoDescripcion.setText(null);
            campoTextoPrecio.setText(null);
        }else if(botonCancelar.getText().equals("Eliminar")) {
            productos.eliminar(Integer.parseInt(tablaProductos.getValueAt(tablaProductos.getSelectedRow(), 0).toString()));
            botonAgregar.setText("Agregar");
            botonCancelar.setText("Cancelar");
        }
        
        actualizarVentana();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextArea campoTextoDescripcion;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JTextField campoTextoPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
    private IProductosDAO productos;
    private IConexionDB conexion;
    private Conversion conversion;

}
